export enum GameType {
  CRASH = "CRASH",
  BLACKJACK = "BLACKJACK",
  ROULETTE = "ROULETTE",
  PLINKO = "PLINKO",
  TOWERS = "TOWERS",
  REME = "REME",
  DICE = "DICE",
  COINFLIP = "COINFLIP",
  MINES = "MINES",
  LIMBO = "LIMBO",
  KENO = "KENO",
}
